### ISSUE TITLE
Variable evaluation bug ?

### ISSUE THREAD

**Issue by nagy** [hemml/OMGlib#2]
I am having some trouble understanding whether the following is a bug or not.

Say, I have a an init file like this:

```
(require :omg)
(defpackage :my-test (:use cl omg omgui jscl))
(in-package :my-test)

(defparameter-f *some-data* #(1 2 3))

(defun-f some-function ()
  (jslog *some-data*)
  (length *some-data*))

(defun-r my-boot ()
  (jslog (some-function)))

(add-to-boot '(my-boot))

(restart-server)
```

I executed that code above via sly and pointed a browser at it. When I then empty the list:

```
CL-USER> (in-package :my-test)
#<PACKAGE "MY-TEST">
MY-TEST> (defparameter-f *some-data* nil)
NIL
MY-TEST>
```

My expectation would be that `(some-function)` now returns `0`. But instead I get:

```
MY-TEST> (remote-exec '(some-function))
(3)
MY-TEST> (remote-exec '*some-data*)
(NIL)
MY-TEST>
```

You can see that the function return value is wrong, but the data behind it got updated correctly.
Is this expected behavior? If not, is there some way I can help in fixing this?

I suspect this has something todo with how javascript closes over its function values:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by hemml** [comment]
This is because the variables, defined via `defparameter-f` cannot be synchronized in real-time, because there is no way to detect variable change in CL without huge overhead.
Your program will work in the following way:

1. Browser connects to the host.
2. The host sending boot command: `EXEC: (eval '(my-boot))`
3. Browser finds that `#'my-boot` is undefined and asking the host for the code: `GIMME 'my-boot`
4. Host finds what #'my-boot is -r function (RPC), compiles and returns the code: `EXEC (defun my-boot () (rpc-call 'my-boot))`
5. Browser gets the code and executes it: `CALL_RPC '(my-boot)`
6. Host executes `my-boot`, in the first line this is -f function `jslog`, so it again asking the browser: `EXEC: '(jslog (some-function))`
7. Browser don't have a definitions for `jslog` and `some-function` and asked the host, getting `(defun jslog ...)` and `(defun some-function ...)`, `some-function` asking for `*some-data*` and getting `(defparameter *some-data* ...)`, `jslog` is already defined, so it will be just executed. Browser executes all of the code and returns the result of `some-function`.
8. You are changing the *some-data*, but the browser will not ask for update, because it already has the symbol `*some-data*` defined. Your second call of the browser-side function will return the old value.

If you need for synchronous updates of the data you have to wrap it around with getter and setter functions. If you want to store the "master" value on the host, define the functions as RPC via `defun-r`, otherwise use `defun-f` for browser-side.

**Comment by nagy** [comment]
Thank you for the detailed explanation, but I still dont understand the issue. I do not think this is an issue of synchronisation between the server and the browser, but rather a reevaluation problem in the browser alone.

> 8. You are changing the `*some-data*`, but the browser will not ask for update, because it already has the symbol `*some-data*` defined. Your second call of the browser-side function will return the old value.

With my call of `(defparameter-f *some-data* ...)` the browser already knows about the new value, as you can see with this output:

```
MY-TEST> (remote-exec '*some-data*)
(NIL)
MY-TEST> 
```

And since the call to `(some-function)` on the browser side returned `3` it means that there is still some old version of `*some-data*` lingering around.

I was having success by wrapping everything in `(eval '*some-data*)` , which is similar to the getter/setter version you proposed, but it is a bit unfortunate.

Here is a screenshot from the browserconsole showing the same thing:

![omglib-eval](https://user-images.githubusercontent.com/692274/134817943-86a789f5-4101-4989-99f2-d27b51fbfe58.png)

**Comment by hemml** [comment]
If you look at the network activity, it will be more clear. JSCL in the browser is also a Lisp, it works independently from the host, but in the case of `undefined symbol` conditions (not the real conditions are used, because JSCL lacks the support, OMG just injects some hooks in JSCL code) it will ask the host for the symbol code. If the symbol is already fetched, it will not be asked again. Technically it is possible to do this, but the performance will be terrible, because any access to the symbol will trigger HTTP-call.

**Comment by nagy** [comment]
I am being appreciative of the whole project and of your valuable time, but with the risk of sounding too pushy, I would try to restate my emphasis somehow, that I do not think this has anything to do with networking at all.

Please ignore the previous initfile and functions. This initfile should be enough:

```lisp
(require :omg)
(defpackage :my-test (:use cl omg omgui jscl))
(in-package :my-test)
(restart-server)
```

Now, in sly ( the host lisp ), I will define three separate functions, while evaluating each and in-between changing a variable, that they all access. A browser is connected.

```
CL-USER> (in-package :my-test)
#<PACKAGE "MY-TEST">
MY-TEST> (defparameter-f *data* #(1 2 3))
NIL
MY-TEST> (defun-f func1 () (length *data*))
;; elided
MY-TEST> (func1)
(3)
MY-TEST> (defparameter-f *data* #(1 2 3 4))
NIL
MY-TEST> (defun-f func2 () (length *data*))
;; elided
MY-TEST> (func2)
(4)
MY-TEST> (defparameter-f *data* #(1 2 3 4 5))
NIL
MY-TEST> (defun-f func3 () (length *data*))
;; elided
MY-TEST> (func3)
(5)
MY-TEST> (list (func1) (func2) (func3))
((3) (4) (5))
MY-TEST> 
```

As you can see **each function stores its own copy of `*data*`, and I dont think this is correct**. This is also not just a result of using sly, since I can verify the same result in the browser as well.

There is also no need for any networking activity here, since the browser already knows the most up-to-date version of `*data*`.

> JSCL in the browser is also a Lisp, it works independently from the host,

I know, and when verifying those return-values in the browser-console, I get the same result.

**Comment by hemml** [comment]
Hmmm. This is very interesting.
All of the functions must return `(3)` in my opinion if there was no browser reconnections.
May be this is a bug, but I'm not sure, may be it will be better to document this behavior:

OMG has a mechanism of notification if some browser-side stuff is being redefined. It sends to all connected browsers a command to delete `*data*` every time when you invoke defparameter-f. If you will use `setf` to modify `*data*` the library will not do this and you will see `(3)` as a result of all your functions.

What is happened in your case: when each function is compiled to JS, it will get a reference to `*data*` symbol, which is still retained after the symbol deletion when you call `defparameter-f` again. The new function will get a reference to a new  exemplar of `*data*`, while first one still has an old one.

May be it will be better to disable this invalidation mechanism in next version, it was never worked well :)

Thank you for your detective work!

**Comment by hemml** [comment]
I think, I have fixed the `remote-unintern` function behavior, now call of the `defparameter-f` doesn't delete symbol, but just changing existing one. Please check your code with the latest commit, now all functions must return the same value.

**Comment by nagy** [comment]
Everything works great, thank you very much!

Unfortunately the export of `defconstant-f` got lost in its way, but this issue can be closed.

**Comment by hemml** [comment]
oops, I have accidentally commited code from my home computer, sorry) Returned `defconstant-f` back again, thank you!
